### ISSUE TITLE
Adoption into Plesk official Extension Library

### ISSUE THREAD

**Issue by DerDanilo** [firstred/plesk-cloudflare#1]
Awesome, finally someone build a simple extension to sync the DNS records only!
I couldn't get my head around with the Cloudflare ServerShield extension, since it does not what is only required for DNS sync.

Have you considered to push this extension into the official Plesk Extension Library? You could even ask for 2,50 €/Month or something for people to use it if you wanted, to support your time to keep it working.

I have contacts with Plesk Core Devs and could possibly connect you. 

Thanks for considering!

**Comment by firstred** [comment]
Haha, it's that one feature you would've expected in the ServerShield extension, right? ^^

> Have you considered to push this extension into the official Plesk Extension Library?

I have not, never knew that was an option, but I will look into it. Thanks for the suggestion and great to hear that the extension has helped you out!

**Comment by DerDanilo** [comment]
I have connections to some developer and C members of Plesk. Please check my website to PM me.
